listener 1883
allow_anonymous false
password_file /mosquitto/config/passwd
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
log_type all

# Bridge to global Meshtastic MQTT
connection meshtastic-global
address mqtt.meshtastic.org:1883
remote_username meshdev
remote_password large4cats
topic msh/EU_868/# in 0 "" ""
topic msh/2/e/# in 0 "" ""
bridge_attempt_unsubscribe true
cleansession true
try_private false
notifications false
bridge_protocol_version mqttv311
