-- Extend telemetry table with all sensor types
-- Power Metrics (INA219/INA260 - external power monitoring)
ALTER TABLE telemetry ADD COLUMN IF NOT EXISTS ch2_voltage DOUBLE PRECISION;
ALTER TABLE telemetry ADD COLUMN IF NOT EXISTS ch2_current DOUBLE PRECISION;
ALTER TABLE telemetry ADD COLUMN IF NOT EXISTS ch3_voltage DOUBLE PRECISION;
ALTER TABLE telemetry ADD COLUMN IF NOT EXISTS ch3_current DOUBLE PRECISION;

-- Environment Metrics (weather stations, environmental sensors)
ALTER TABLE telemetry ADD COLUMN IF NOT EXISTS gas_resistance DOUBLE PRECISION;
ALTER TABLE telemetry ADD COLUMN IF NOT EXISTS iaq INTEGER;
ALTER TABLE telemetry ADD COLUMN IF NOT EXISTS distance DOUBLE PRECISION;
ALTER TABLE telemetry ADD COLUMN IF NOT EXISTS lux DOUBLE PRECISION;
ALTER TABLE telemetry ADD COLUMN IF NOT EXISTS white_lux DOUBLE PRECISION;
ALTER TABLE telemetry ADD COLUMN IF NOT EXISTS ir_lux DOUBLE PRECISION;
ALTER TABLE telemetry ADD COLUMN IF NOT EXISTS uv_lux DOUBLE PRECISION;
ALTER TABLE telemetry ADD COLUMN IF NOT EXISTS wind_direction INTEGER;
ALTER TABLE telemetry ADD COLUMN IF NOT EXISTS wind_gust DOUBLE PRECISION;
ALTER TABLE telemetry ADD COLUMN IF NOT EXISTS wind_lull DOUBLE PRECISION;
ALTER TABLE telemetry ADD COLUMN IF NOT EXISTS weight DOUBLE PRECISION;
ALTER TABLE telemetry ADD COLUMN IF NOT EXISTS radiation DOUBLE PRECISION;
ALTER TABLE telemetry ADD COLUMN IF NOT EXISTS rainfall_1h DOUBLE PRECISION;
ALTER TABLE telemetry ADD COLUMN IF NOT EXISTS rainfall_24h DOUBLE PRECISION;
ALTER TABLE telemetry ADD COLUMN IF NOT EXISTS soil_moisture DOUBLE PRECISION;

-- Air Quality Metrics (PM sensors, CO2, VOC, NOx)
ALTER TABLE telemetry ADD COLUMN IF NOT EXISTS pm100_standard INTEGER;
ALTER TABLE telemetry ADD COLUMN IF NOT EXISTS co2 INTEGER;
ALTER TABLE telemetry ADD COLUMN IF NOT EXISTS voc_idx INTEGER;
ALTER TABLE telemetry ADD COLUMN IF NOT EXISTS nox_idx INTEGER;

-- Metadata flags to track which sensors are present on each node
ALTER TABLE telemetry ADD COLUMN IF NOT EXISTS has_power_metrics BOOLEAN DEFAULT FALSE;
ALTER TABLE telemetry ADD COLUMN IF NOT EXISTS has_environment_metrics BOOLEAN DEFAULT FALSE;
ALTER TABLE telemetry ADD COLUMN IF NOT EXISTS has_air_quality_metrics BOOLEAN DEFAULT FALSE;

-- Also add sensor capability tracking to nodes table
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS has_power_sensor BOOLEAN DEFAULT FALSE;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS has_environment_sensor BOOLEAN DEFAULT FALSE;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS has_air_quality_sensor BOOLEAN DEFAULT FALSE;
